language: node_js

node_js:
  - '6.2.1'

env:
  - CSSOBJ_GENCSS='../node_modules/cssobj-plugin-post-gencss/dist/cssobj-plugin-post-gencss.cjs.js'

script: 'npm install cssobj/cssobj-plugin-post-gencss && npm test'
